const FRONTEND_ROUTES = {
    BASE: '/',
    ADMIN: {
        BASE: '/admin-panel',
        PARTNERS: '/admin-panel/partners',
        NEW_STREETCODE: '/admin-panel/new-streetcode',
        EDIT_STREETCODE: '/admin-panel/edit-streetcode',
        DICTIONARY: '/admin-panel/dictionary',
        FOR_FANS: '/admin-panel/for-fans',
        LOGIN: '/admin-panel/login',
        RESET_PASSWORD: '/admin-panel/reset-password',
        TEAM: '/admin-panel/team',
        ANALYTICS: '/admin-panel/analytics',
        NEWS: '/admin-panel/news',
        STREETCODES: '/admin-panel/streetcodes',
        EDITOR: '/admin-panel/editor',
        CALENDAR: '/admin-panel/calendar',
        VACANCIES: '/admin-panel/vacancies',
        SETTINGS: '/admin-panel/settings',
    },
    ADMIN_RELATIVE: {
        PARTNERS: 'partners',
        TEAM: 'team',
        STREETCODES: 'streetcodes',
        FOR_FANS: 'for-fans',
        DICTIONARY: 'dictionary',
        EDITOR: 'editor',
        CALENDAR: 'calendar',
        NEWS: 'news',
        VACANCIES: 'vacancies',
        SETTINGS: 'settings',
    },
    OTHER_PAGES: {
        CATALOG: '/catalog',
        ERROR404: '/404',
        PRIVACY_POLICY: '/privacy-policy',
        CONTACT_US: '/contact-us',
        PARTNERS: '/partners-page',
        SUPPORT_US: '/support-us',
        NEWS: '/news',
    },
};

export default FRONTEND_ROUTES;
